baseURL = "https://jabpcomplex.github.io/"
languageCode = ''
title = 'Ciencia y Sociedad'
theme = "tale"
googleAnalytics = "UA-133700000-0"

[Author]
   name = "Julio Alberto"

[Params]
css = ["custom.css"]

disqusShortname = "disqus-example"

[menu]
   [[menu.main]]
     identifier = "contacto"
     name = "Contacto"
     title = "Contacto"
     url = "/Contacto/"
     weight = 0
  [[menu.main]]
     identifier = "posts"
     name = "Posts"
     title = "Posts"
     url = "/posts/"
     weight = 0 
